# World parameters
NUM_AGENTS = 40
AGENT_SLACK = 7
# Number of cells in the environment
WORLD_WIDTH = 30
WORLD_HEIGHT = 30

# Infection parameters
INITIAL_INFECTED_PERCENT = 0.02
INFECTION_RADIUS = 2

INCUBATION_SAFE_TIME = 5
INCUBATION_CONTAGIOUS_TIME = 5
SYMPTOMATIC_TIME = 10

INFECTION_PROBABILITY = 1
