@startuml Model_C_Contact_Tracing
left to right direction
skinparam DefaultFontName ArialMT

state Agent {
    [*] -down-> Idle
    ' note left of Idle
    '     Shift between home
    '     and work points
    '     every 12 hours
    ' end note
    Idle --> AwaitingTest : Become symptomatic
    Idle --> SelfIsolating : Notified of contact with symptomatic agent
    AwaitingTest : notify_contacts()
    AwaitingTest --> SelfIsolating : Testing delay expires

    SelfIsolating --> Idle : Recovery
}

@enduml