@startuml Two_Stage_Infection
skinparam DefaultFontName ArialMT

state Infection {
    [*] --> Susceptible
    Susceptible --> Incubating : infect()
    Incubating : advance_infection()
    Incubating --> Contagious : advance_infection()
    Contagious : advance_infection()
    Contagious --> SymptomaticMild : advance_infection()
    SymptomaticMild : advance_infection()
    SymptomaticMild -right-> SymptomaticSevere : advance_infection()
    SymptomaticMild --> Susceptible : false alarm
    SymptomaticSevere : advance_infection()
    SymptomaticSevere -up-> Recovered : advance_infection()
    Recovered: lose_imminuty()
    Recovered -left-> Susceptible : immunity expires
}

@enduml